# Copyright (c) 2025 Felix Kahle.
#
# Permission is hereby granted, free of charge, to any person obtaining
# a copy of this software and associated documentation files (the
# "Software"), to deal in the Software without restriction, including
# without limitation the rights to use, copy, modify, merge, publish,
# distribute, sublicense, and/or sell copies of the Software, and to
# permit persons to whom the Software is furnished to do so, subject to
# the following conditions:
#
# The above copyright notice and this permission notice shall be
# included in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
# MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
# NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE
# LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION
# OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION
# WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

name: Build and Release

permissions:
  contents: write

on:
  push:
    tags: ["v*"]

jobs:
  build:
    name: Build for ${{ matrix.job.target }}
    runs-on: ${{ matrix.job.os }}
    strategy:
      fail-fast: true # Stop all builds if any test fails
      matrix:
        job:
          - {
              os: ubuntu-latest,
              target: x86_64-unknown-linux-gnu,
              name: linux-x64,
            }
          - {
              os: windows-latest,
              target: x86_64-pc-windows-msvc,
              name: windows-x64,
            }
          - { os: macos-latest, target: x86_64-apple-darwin, name: macos-x64 }
          - {
              os: macos-latest,
              target: aarch64-apple-darwin,
              name: macos-arm64,
            }

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Ensure tag is on main
        shell: bash
        run: |
          git fetch origin main
          if git merge-base --is-ancestor origin/main HEAD; then
            echo "Tag commit is on main. Continuing."
          else
            echo "Tag commit is NOT on main. Exiting."
            exit 1
          fi
      - uses: dtolnay/rust-toolchain@master
        with:
          components: rustfmt, clippy
          targets: ${{ matrix.job.target }}

      - name: Run Tests
        run: cargo test --release --package bollard_ffi --target ${{ matrix.job.target }}

      - name: Build
        run: cargo build --release --package bollard_ffi --target ${{ matrix.job.target }}

      - name: Package (Unix)
        if: runner.os != 'Windows'
        run: |
          mkdir -p dist/lib
          cp target/${{ matrix.job.target }}/release/libbollard_ffi.* dist/lib/
          cd dist && tar -czvf ../bollard-${{ matrix.job.name }}.tar.gz .

      - name: Package (Windows)
        if: runner.os == 'Windows'
        run: |
          mkdir dist\bin
          copy target\${{ matrix.job.target }}\release\bollard_ffi.dll dist\bin\
          tar -czvf bollard-${{ matrix.job.name }}.tar.gz -C dist .

      - name: Upload to Release
        uses: softprops/action-gh-release@v2
        with:
          files: bollard-${{ matrix.job.name }}.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
